name: Run Renovate

on:
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify Docker is available
        run: docker --version

      - name: Run Renovate
        run: ./run-renovate.sh
